spring.application.name=auth-service

server.port=8081


# Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Flyway
spring.flyway.enabled=true


# Actuator
management.endpoints.web.exposure.include=health,info

# JWT
jwt.secret=4Z8r9kL2mQ7xN5pT8vW1yB6cF3hJ9sR4X2zA7nM5qP8dL1uK6wE0tY3iO9cV2bN7
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Seeder
app.admin.username=admin
app.admin.email=admin@jastip.com
app.admin.password=Admin123!